# Generated by Django 5.2 on 2025-04-30 15:55

from django.db import migrations

# This code is adapted from the Django documentation, 
# specifically for creating custom migrations and seeding data.
# URL: https://docs.djangoproject.com/en/5.2/topics/migrations/#data-migrations

def create_genres(apps, schema_editor):
    Tag = apps.get_model('movielix', 'Tag')
    genres = [
        "Action", "Adventure", "Animation", "Biography", "Comedy", "Crime",
        "Documentary", "Drama", "Family", "Fantasy", "History", "Horror",
        "Music", "Musical", "Mystery", "Romance", "Sci-Fi", "Sport",
        "Thriller", "War", "Western"
    ]
    for genre in genres:
        Tag.objects.get_or_create(name=genre)
        
        
class Migration(migrations.Migration):

    dependencies = [
        ('movielix', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_genres),
    ]
